version: '3.5'
services:
  app:
    build: .
  sut:
    image: alpine:3.20
    depends_on:
      - app
    command: /tmp/run_tests.sh
    ports:
      - 8080:8080
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
